version: '3.9'
services:

  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: [ "sh", "-c", "/strv-go-newsletter-shakleya-mohammed/bin/migrate up && /strv-go-newsletter-shakleya-mohammed/bin/api" ]
    restart: always

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dbuser -d dbname" ]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always