package repository

import (
	"context"

	"firebase.google.com/go/v4/db"
	"gorm.io/gorm"

	"github.com/bwc00/strv-go-newsletter-shakleya-mohammed/api/resource/subscription"
	"github.com/bwc00/strv-go-newsletter-shakleya-mohammed/api/resource/newsletter"
)

type Repository struct {
	postgresDB *gorm.DB
	firebaseDB *db.Ref
}

func NewRepository(postgresDB *gorm.DB, firebaseDB *db.Ref) *Repository {
	return &Repository{
		postgresDB: postgresDB,
		firebaseDB: firebaseDB,
	}
}


func (r *Repository) ListSubscriptions() (*[]subscription.Subscription, error) {
	subscriptionsRef := r.firebaseDB.Child("subscriptions")

	results, err := subscriptionsRef.OrderByKey().GetOrdered(context.Background())
	if err != nil {
	        return nil, err
	}
	subscriptions := make([]subscription.Subscription, len(results))
	for i, r := range results {
		var subscription subscription.Subscription
		if err := r.Unmarshal(&subscription); err != nil {
			return nil, err
		}
		subscriptions[i] = subscription
	}

	return &subscriptions, nil
}

func (r *Repository) Subscribe(SubscriptionInfo *subscription.Subscription) (string, error) {
	//check if newsletter exists
	if err := r.postgresDB.Where("id = ?", SubscriptionInfo.NewsletterID).First(&newsletter.Newsletter{}).Error; err != nil {
		return "", err
	}

	subscriptionsRef := r.firebaseDB.Child("subscriptions")

	// Add subscription
	newSubscriptionRef, err := subscriptionsRef.Push(context.Background(), SubscriptionInfo)
	if err != nil {
		return "", err
	}

	// Get the unique key generated by Push()
	subscriptionID := newSubscriptionRef.Key

	return subscriptionID, nil
}

func (r *Repository) Unsubscribe(subscriptionID string) error {

	subscriptionRef := r.firebaseDB.Child("subscriptions").Child(subscriptionID)

	// Remove subscription
	err := subscriptionRef.Set(context.Background(), nil)

	return err
}